options:
  headless: true
  sloMo: 250
jobs:
  - name: hoge fuga site scraiping
    baseUrl: https://example.com
    enabled: false
    steps:
      - command: Goto
        name: go to login form
        url: /login
      - command: WaitForNavigation
      - command: SetInput
        name: input mail address
        selector: "#mail"
        value: example@example.com
      - command: SetInput
        name: input password
        selector: "#passwored"
        value: password
      - command: Click
        name: login execution
        selector: "#login"
      - command: WaitForSelector
        name: wait for
        selector: ""
