dstp:
  options:
    headless: false
    sloMo: 250
  tasks:
    name: test
    baseUrl: https://example.com
    enabled: true
    commands:
      goto:
        url: 'a'
      input:
        field:
          selector: b
          value: a
