dstp:
  settings:
    headless: false
    sloMo: 250
  difinitions:
    name: test
    baseUrl: https://example.com
    enabled: true
    routes:
      goto:
        url: 'a'
      input:
        field:
          selector: b
          value: a
